[package]
name = "hello_2018"
version = "0.0.0"
workspace = "../../"
publish = false
edition = "2018"

[dependencies]
rocket = { path = "../../core/lib" }
rocket_codegen = { path = "../../core/codegen" }
